#Topics to cover
0. End to end Scikitlearn workflow
1. Getting the data ready.
2. Choose the right estimator or algorithms to our problems.
3. Fit the model/algorithms and use it to make the predictions on our data.
4. Evaluating the model.
5. Improve the model.
6. Save and load the trained model.
7.Improve the model

##0. An end to end Scikit learn workflow

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [26]:
#Create X (features matrix)
x = heart_disease.drop("target",axis=1)
#Create Y (Labels)
y = heart_disease["target"]

In [14]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
#choose the right model and parameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
#we'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [38]:
#fit the model tp the training data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x , y , test_size=0.2)

In [46]:
clf.fit(x_train , y_train)

RandomForestClassifier()

In [48]:
#Making Predictions
y_preds = clf.predict(x_test)
y_preds

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [50]:
y_test

290    0
159    1
167    0
51     1
224    0
      ..
222    0
57     1
211    0
256    0
42     1
Name: target, Length: 61, dtype: int64

In [54]:
#4. Evaluate the model on training and test data
clf.score(x_train,y_train)


1.0

In [56]:
clf.score(x_test,y_test)

0.8524590163934426

In [60]:
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.87      0.84      0.85        31
           1       0.84      0.87      0.85        30

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



In [62]:
confusion_matrix(y_test,y_preds)

array([[26,  5],
       [ 4, 26]], dtype=int64)

In [64]:
accuracy_score(y_test,y_preds)

0.8524590163934426

In [66]:
#Improve Our Model
#try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators")
    clf = RandomForestClassifier(n_estimators = i).fit(x_train , y_train)
    print(f"Model Accuracy on test set: {clf.score(x_test , y_test)*100:.2f}%")
    print("")

Trying model with 10 estimators
Model Accuracy on test set: 80.33%

Trying model with 20 estimators
Model Accuracy on test set: 86.89%

Trying model with 30 estimators
Model Accuracy on test set: 80.33%

Trying model with 40 estimators
Model Accuracy on test set: 81.97%

Trying model with 50 estimators
Model Accuracy on test set: 80.33%

Trying model with 60 estimators
Model Accuracy on test set: 83.61%

Trying model with 70 estimators
Model Accuracy on test set: 83.61%

Trying model with 80 estimators
Model Accuracy on test set: 81.97%

Trying model with 90 estimators
Model Accuracy on test set: 85.25%



In [68]:
#save the model and load it
import pickle
pickle.dump(clf,open("random_forest_model_1.pk1","wb"))

In [73]:
load_model = pickle.load(open("random_forest_model_1.pk1","rb"))
load_model.score(x_test,y_test)

0.8524590163934426

In [16]:
import sklearn 
sklearn.show_versions()


System:
    python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\91979\anaconda3\python.exe
   machine: Windows-11-10.0.26100-SP0

Python dependencies:
      sklearn: 1.4.2
          pip: 24.0
   setuptools: 69.5.1
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: None
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.2
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\91979\anaconda3\Library\bin\mkl_rt.2.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 6
threading_layer: intel

       filepath: C:\Users\91979\anaconda3\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12


In [16]:
# 1. Getting our data ready to be used with machine learning

# Three main things to do:
# 1. Split the data into features and labels ('X' and 'Y')
# 2. Filling or disregarding the missing values
# 3. Converting non numeric values into numeric values also called feature encoding.

In [18]:
x = heart_disease.drop('target',axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [20]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [30]:
#Split the data into training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [24]:
x_train.shape ,x_test.shape ,y_train.shape ,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [44]:
### 1.1Make sure it's all numerical 

In [10]:
car_sales = pd.read_csv('car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [14]:
x = car_sales.drop('Price',axis = 1)
y = car_sales["Price"]

In [18]:
#Split the data into training and test
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2)

In [30]:
#Turning all categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make" , "Colour" , "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder = 'passthrough')
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [32]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [34]:
#Refit the model
np.random.seed(42)
x_train , x_test , y_train , y_test = train_test_split(transformed_x , y , test_size = 0.2)
model.fit(x_train,y_train)

RandomForestRegressor()

In [36]:
model.score(x_test,y_test)

0.3235867221569877